### ISSUE TITLE
Provide a way to create "namespaced" log objects

### ISSUE THREAD

**Issue by jcready** [npm/npmlog#11]
I'd like a way to create "namespaced" loggers which would eliminate the need to provide the `prefix` to the log methods. Here's how I'd imagine it working:

``` javascript
var npmlog = require('npmlog');
// This is the type of method I'd like added to npmlog proper
npmlog.ns = function namespaceLogger(namespace){
  var logger = {};
  for (var k in this.levels) {
    logger[k] = this[k].bind(this, namespace);
  }
  return logger;
}

var customLog = npmlog.ns('Custom');
customLog.info('Hello %s!', 'World');
// >> info Custom Hello World!
```

Obviously this only supports the `log[level](prefix, message, ...)` syntax, but it could probably be improved to support all the npmlog methods.

**Comment by matthias-reis** [comment]
I would prefer something like the curried solutions of other libraries like:

```
var log = require('npmlog')('namespace');
...
log('This is logged with namespace')
```

**Comment by wraithgar** [comment]
Closing due to age
