### ISSUE TITLE
npmlog is at v1.0.0? 

### ISSUE THREAD

**Issue by springmeyer** [npm/npmlog#15]
I see that npmlog is reporting v1.0.0 at https://www.npmjs.com/package/npmlog but the latest tag at https://github.com/npm/npmlog/releases lists v0.1.1 and so does [package.json](https://github.com/npm/npmlog/blob/master/package.json#L5).

Was a 1.0.0 release issued but no tag pushed to github? Or was a 1.0.0 release published accidentally?

/cc @iarna

**Comment by zeke** [comment]
Looks like 1.0 is in the registry: http://registry.npmjs.org/npmlog -- I bet it was a forgotten git tag push.

@iarna is in bed with a headache today :(

**Comment by springmeyer** [comment]
Thanks @zeke - also just noticed https://github.com/rvagg/pangyp/commit/a9688cdcf36ee12e7004a5feb0d8fc3e7be8ed52, so clearly not a mistake. I was confused about the difference between 0.x and 1.x in the first place (so I could figure out whether to upgrade npmlog in node-pre-gyp). This is why I arrived here and then noticed the lack of any sign of 1.x. But no worries now that I know 1.x is just getting on the right side of semver.
