### ISSUE TITLE
Can I use this with carriage return?

### ISSUE THREAD

**Issue by donaldpipowitch** [npm/npmlog#18]
I spawn a child process (protractor) which logs to `stdout` with a carriage return, but I don't know how to use it with npmlog, because it logs to a new line instead of replacing the old one.

I would like to do this:

```
    var child = spawn(getProtractorBinary('protractor' + ws.winExt), [ path ], {
      env: process.env
    });

    child.stdout.on('data', data => {
      log.info('protractor', data.toString());
    });
```

Instead I need to do this:

```
    var child = spawn(getProtractorBinary('protractor' + ws.winExt), [ path ], {
      env: process.env,
      stdio: [ 'pipe', process.stdout, 'pipe' ]
    });
```

Any way to combine logs with carriage return in npmlog?

**Comment by wraithgar** [comment]
Closing due to age
