### ISSUE TITLE
stderr for logs?

### ISSUE THREAD

**Issue by jdalton** [npm/npmlog#25]
I may be reading the code wrong but it looks like warnings are sent to `stderr`.
I think this may be causing issues for some folks with the lodash deprecation message as it causes a non-`0` exit code.

<img src=https://cloud.githubusercontent.com/assets/4303/11546345/8bba705e-9901-11e5-841d-dc5d5cb892b7.png height=70% width=70%>

\cc @phated

**Comment by jdalton** [comment]
\cc @phated

**Comment by phated** [comment]
Not sure why I am copied on this. I don't maintain globule.

**Comment by jdalton** [comment]
Hey @phated! I cc'd you in case you've seen an increase in issues reported to gulp.

**Comment by othiym23** [comment]
Indeed, `npmlog` sends its output to `stderr`, and always has. This is by design and pretty much an immutable facet of `npmlog` / npm's design at this point, as all kinds of assumptions are based on diagnostics, warnings, and errors going to stderr and expected "regular" output going to stdout.

**Comment by jdalton** [comment]
Am I mistaken or is everything [going through stderr](https://github.com/npm/npmlog/blob/master/log.js#L9-L10)?

Am I the odd one out thinking that it's odd to treat a warn as an error?

**Comment by othiym23** [comment]
It's diagnostic output, so it goes through the diagnostic output channel. Pretty sure I'm nearly directly quoting @isaacs there.

Practically, this has many useful implications, like being able to pipe npmlog separately from the expected output of the command, and like I said, it's literally always worked this way, and changing it now would wreak the kind of havoc I don't even really want to think about, because large piles of tooling are built on it.

**Comment by jdalton** [comment]
Cool. I'll ping back if I hear of anymore issues.
I tried getting a bit more info but haven't had much luck.

Here I stated that warnings shouldn't affect functionality to which the user replied:

<img width="70% height="70%"  src="https://cloud.githubusercontent.com/assets/4303/11547087/3574d3e2-9906-11e5-960c-22f3fbe3fb98.png">

**Comment by othiym23** [comment]
Yes, PowerShell helpfully sets the exit status to error for you when there's stuff printed to stderr, which I guess means other MS tools do as well. Too bad we don't know anybody who works at Microsoft...

**Comment by jdalton** [comment]
> Yes, PowerShell helpfully sets the exit status to error for you when there's stuff printed to stderr, which I guess means other MS tools do as well. 

Have you had many issues reported as a result?

> Too bad we don't know anybody who works at Microsoft...

LOL, I'll see what I can stir up.

**Comment by othiym23** [comment]
Just one so far, which is how I know about the issue, and that was somebody wanting us to suppress some other (spurious) warning so that their build wouldn't fail, so a similar situation.

**Comment by thylong** [comment]
It seems like yarn is behaving differently :
https://github.com/yarnpkg/yarn/blob/master/src/reporters/console/console-reporter.js#L135
