### ISSUE TITLE
How to include method name and line number in logger

### ISSUE THREAD

**Issue by sravanmedarapu** [npm/npmlog#29]
any possibility to include **method name** and **line number** in logger

**Comment by abhicgupta** [comment]
You can write a simple library over npmlog which can prepend the method name and line number in every message that you log.  

For fetching method name and line number, you can refer the following link

http://stackoverflow.com/questions/11386492/accessing-line-number-in-v8-javascript-chrome-node-js

**Comment by sravanmedarapu** [comment]
Thanks, will give a try :+1:

**Comment by helio-frota** [comment]
hi, this can be closed ?
or can be a feature request ?
