### ISSUE TITLE
Unnecessary processing incase the log level is lower than the set level.

### ISSUE THREAD

**Issue by samarthmed** [npm/npmlog#36]
I set the log level to "INFO" on production systems .

My code had a lot of verbose statements spread across it and in some cases , there was a massive json placed inside the logger. This led to a severe spike in latency on the average response times.

There already is an option of not writing to the stdout if the statement log level is lower than the general setting but we still do a lot of unnecessary processing in the log.log function (the culprit in my case was util.format) 

Can we had the log level check in the log.log function itself ? Or is there some reason that you've added this in the emitLog function ? 

Thanks .

**Comment by iarna** [comment]
As I said over in #39, we need that where it is because we need `log.record` to have all log levels so that `npm-debug.log` files produced on crash can contain useful information. As things are structured today, I don't see a way to save you that computation. =/
