### ISSUE TITLE
Requiring npmlog enables gauge, even if gauge is never used

### ISSUE THREAD

**Issue by murgatroid99** [npm/npmlog#43]
When you `require('npmlog')`, it creates a `Gauge`, which by default starts out enabled. This calls `setInterval` with (by default) a 50ms interval. When the gauge is never used, this can have negative effects on performance for no benefit.

Please have the guage start out disabled, and only enable it the first time that you actually need it.

**Comment by wraithgar** [comment]
just checked the source, gauge is instantiated now with `enabled: false`
