### ISSUE TITLE
Log messages flushing after tasks complete

### ISSUE THREAD

**Issue by dfreeman** [npm/npmlog#45]
Hi! Apologies if this turns out the be the wrong repo to file this against — I haven't fully wrapped my head around the interplay between `npmlog`, `gauge`, `are-we-there-yet` and the stuff in npm's `install` command that wraps that all together.

We found in https://github.com/ember-cli/ember-cli/pull/6306 that some final messages/progress bar updates are being printed _after_ the callback given to npm's `install` command has been invoked. It looks as though no new messages are being emitted from npm after the callback is called, but the periodic flushing of queued up messages continues more or less on autopilot.

I'd be happy to put together a PR to prevent that from happening, but wanted to check in before I spend too much time going down the wrong rabbithole — are there changes to be made here or in one of the other constituent libraries to handle this scenario, or are there additional steps that need to be taken on npm's side to either force a flush or drop the queued updates?

**Comment by iarna** [comment]
What you're seeing here isn't (I think) related to the complexities of these various modules. `npmlog` doesn't actually do any buffering of its own. `log.pause` will cause it to queue up log lines but `log.resume` _immediately_ writes them. Relatedly, `gauge` just writes directly to its output stream

That being said, Node.js streams _do_ buffer and if you want to avoid that you'll have to tune down the `highWaterMark` on your output stream. By default the output stream is `process.stderr` which has Node.js version/platform specific semantics unfortunately.

But this points to a bigger problem– if you're running into this I suspect you're calling npm's internal API. We don't actually support that. The supported mechanism of interaction is to call it as a command. If you were doing that you'd know that output was fully flushed when the command exited. 

As a bit of an aside, here's a bit on the interaction of these three modules:

`are-we-there-yet` keeps track of overall progress and emits events when that changes.
`gauge` draws the progress bar (at a fixed framerate).
`npmlog` updates the values that `gauge` prints, in part using `are-we-there-yet`'s change event.

**Comment by dfreeman** [comment]
Thanks for taking the time to write up that explanation — that definitely helps clarify the responsibilities among some of the modules at play here.

I understand that Node.js streams buffer, but (assuming I'm following correctly) I think this is unrelated to that. I'd expect streams to be FIFO regardless of buffering, and the issue we were seeing was that progress bar updates were happening after subsequent writes to the same stream.

_I got this far writing up the response, then had a lightbulb moment and went back and played around in the debugger some more_

[This `setInterval` in `gauge`](https://github.com/iarna/gauge/blob/master/index.js#L148) is the source of our issue, since `npmlog`'s `disableProgress` never gets called. Our own process only continues running long enough for one or two more intervals to pass, so it wasn't immediately obvious that it would have kept emitting forever.

I can't take credit/guilt for the original usage of npm as it's being invoked from ember-cli, but that's definitely the issue — npm has no reason internally to disable progress after it's done since normally the next step would be a process exit anyway. I'll close this out since it's not an issue here. Thanks for your patience!
