### ISSUE TITLE
Reentrancy, multiple instances?

### ISSUE THREAD

**Issue by ilg-ul** [npm/npmlog#53]
I took a look at the implementation, and, correct me if I'm wrong, it looks like this (otherwise nice) logger supports only a single instance of a logger, and stores status in the module itself, making it non reentrant, and, as such, unsuitable for server applications, where each user might have a different log level.

Could you consider adding a constructor so that multiple separate instances can be created?

Usage might look like:

```js
const Logger = require('npmlog').Logger
const log = new Logger()
```

Even if this breaks compatibility with existing applications, personally I would completely disable the current non-reentrant usage.

**Comment by zcmgyu** [comment]
I really need this one :(

**Comment by wraithgar** [comment]
closing due to age
