### ISSUE TITLE
Add Typescript definition 💜

### ISSUE THREAD

**Issue by yordis** [npm/npmlog#57]

**Comment by littlepiggy03** [comment]
Thanks to DefinitelyTyped/DefinitelyTyped#25291, this issue should be closed.

**Comment by Bessonov** [comment]
A big `-1` to DefinitelyTyped solution. Typings should be provided with the project itself (or IMHO better convert project to TypeScript). The thing is, typings doesn't help only TypeScript users, but IDEs are able to pick up typings for plain JavaScript projects.
