### ISSUE TITLE
Why resolve stack traces to plain string?

### ISSUE THREAD

**Issue by philraj** [npm/npmlog#62]
Hi,

Is there a particular reason why the stack traces of errors are being turned into strings and duplicated in the log output? It makes errors noisier and harder to read so I'm just trying to figure out if there's a special purpose for this extra formatting.
(https://github.com/npm/npmlog/blob/master/log.js#L182)

**Comment by machinaeXlasse** [comment]
This also made me wonder. Especially the duplicated output is unexpected and it took me some time to trace it back to npmlog.

I see, it is an old issue, but to me it seems like it's woth another look.

**Comment by wraithgar** [comment]
The code has been like this for 10 years and there doesn't appear to be a decision record for it.  If I had to guess it's so that the records array contains only strings.
