### ISSUE TITLE
Example for gauge/tracker usage

### ISSUE THREAD

**Issue by HerHde** [npm/npmlog#63]
Hey folks,
unfortunately I can't figure out how to use the Tracker stuff. I'm trying to display a download progress for example, but I have no Idea how I display the gauge (which brings the feature of overwriting the line, I guess?) or how Tracker items and groups are meant to play together.

Might anybody provide an explanation or example, please?

**Comment by maetulj** [comment]
Hey, a bit late but here is an example how it could work (since no documentation I've done by reading code and trial).

```
const log = require("npmlog");

// Enable usage of progressbar.
log.enableProgress();
log.info("Progress example");

const longProcess = async () => {
    const timeout = (ms) => {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    // New progressbar.
    const b = log.newItem("Something", 100);

    for (let i = 1; i <= 10; i++) {
        await timeout(2000);

        // Diff of completed work.
        b.completeWork(10);
        log.info("Completed", i, b.completed());
    }

    b.finish();
};

longProcess();

// Logged before longProcess is done.
log.info("Done");
```
