### ISSUE TITLE
[BUG] Changelog not updated for v6

### ISSUE THREAD

**Issue by ZebraFlesh** [npm/npmlog#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The CHANGELOG.md file both at HEAD and in the v6.0.0 tag is still the 5.0.1 changelog. It's more difficult to get people to upgrade if they are forced to inspect commit history.

### Expected Behavior

CHANGELOG.md contains list of changes for 6.0.0 release.

### Steps To Reproduce

N/A

### Environment

N/A

**Comment by wraithgar** [comment]
changelog updated

**Comment by ZebraFlesh** [comment]
Thank you for the quick fix!
