### ISSUE TITLE
Hide level, prefix in production

### ISSUE THREAD

**Issue by imjuni** [npm/npmlog#87]
Hi, 

Thank you for cool package.

I want hide level, prefix in production.

```js
import log from 'npmlog';

log.info('iamprefix', 'helloworld!');

// result >> info iamprefix helloworld!
// want >> helloworld!
```

Level, prefix very helpful for development, but not helpful live application. I want hide a level, prefix Like npm.js. But I can't found hide option in README and application source. Is it impossible?

**Comment by wraithgar** [comment]
Where are you seeing the level and prefix not being displayed?

**Comment by imjuni** [comment]
@wraithgar I wan't replace console.log to npmlog log function. At this time I have to use console.log to print production message, and npm log function use to debug message.

**Comment by wraithgar** [comment]
This lib doesn't do that, even the npm cli itself uses console.log when outputting directly to the user for non-logging purposes.
